### PR TITLE
Allow hubot to grant operator status

### PR DESCRIPTION
**Pull request by murrant**
Automatically when mods join.
Or when they ask
`lnms-bot op me`

No testing done :stuck_out_tongue:

### CODE REVIEW

**Comment by laf** [comment]
:)

Is user.name the authenticated value or just the nick (I'm assuming the former).

**Comment by murrant** [comment]
Just Nick I think is there a way to check if it is authenticated?

**Comment by laf** [comment]
You can do /nickserv acc laf

That would respond back and if 3 was at the end the nick is registered.

**Comment by murrant** [comment]
not sure how to do that in hubot-irc :/

**Pull request closed without merging**
